# permissions for end users to edit resourcesyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourcesync-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sinker
    app.kubernetes.io/part-of: sinker
    app.kubernetes.io/managed-by: kustomize
  name: resourcesync-editor-role
rules:
- apiGroups:
  - sinker.influxdata.io
  resources:
  - resourcesyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sinker.influxdata.io
  resources:
  - resourcesyncs/status
  verbs:
  - get
