---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sinker.influxdata.io
  resources:
  - resourcesyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sinker.influxdata.io
  resources:
  - resourcesyncs/finalizers
  verbs:
  - update
- apiGroups:
  - sinker.influxdata.io
  resources:
  - resourcesyncs/status
  verbs:
  - get
  - patch
  - update
